name = "Microfloats"
uuid = "31c70f10-a750-4521-b13c-797315ae2933"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.0.8"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
BitPacking = "b58c8408-13c4-4787-8733-7038ae624acf"

[extensions]
BitPackingExt = "BitPacking"

[compat]
Random = "1"
julia = "1.10"
